{
 "title": "Sockify Nginx Access",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Graphs And Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(request_time_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Time Heatmap (Per/Hour)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (increase(request_time_bucket[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Time Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(request_time_bucket[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests Total Rate (Method)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method) (increase(http_requests_total{job=\"nginx_exporter\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Total Rate (Status)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Body Bytes Sent/Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(body_bytes_sent_total{job=\"nginx_exporter\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(method) (increase(request_length_total{job=\"nginx_exporter\"}[5m])) * -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(request_status_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}